assert(SMODS.load_file("items/jokers/BFDI.lua"))()
assert(SMODS.load_file("items/enhancement.lua"))()
assert(SMODS.load_file("items/spectral.lua"))()
assert(SMODS.load_file("items/tarot.lua"))()
assert(SMODS.load_file("items/planet.lua"))()
assert(SMODS.load_file("items/jokers/BFDIA.lua"))()